spring:
  jackson:
    time-zone: Asia/Tashkent
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: ${APP_NAME:INFO_MONEY}
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:0095}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 15
      validation-timeout: 5000
      max-lifetime: 1800000
      connection-timeout: 50000
      idle-timeout: 600000
      keepalive-time: 900000
      pool-name: depositHikariCP
      register-mbeans: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  messages:
    always-use-message-format: true
  data:
    rest:
      default-page-size: 10
#  servlet:
#    multipart:
#      max-file-size: 200MB
#      max-request-size: 200MB
server:
  port: ${APP_PORT_DEPOSIT:9091}

sentry:
  dsn: https://809f46fddddb00ebd21ad7b4d24b1a26@o4508398301872128.ingest.de.sentry.io/4508408443240528
  environment: "development"
  traces-sample-rate: 1.0    # 1.0 - barcha requestlarni kuzatadi
  debug: false                # Debug rejimini yoqing (faqat test uchun)

currency:
  api:
    url: "https://cbu.uz/uz/arkhiv-kursov-valyut/json/"

logging:
  level:  
    org:
      springframework:
        scheduling=DEBUG:
telegrambot:
  webhook-path: https://scientistically-precongenial-hermila.ngrok-free.dev/webhook # bu yerda  url ni ozgartirib ketin run qilish kerak
  token: 7737977625:AAGqggWlEPqnkIOp52gzkNYTPeeBElMfPhg  # bot token
  username: "@money_management_one_bot"    # bot username
  ## curl -X POST "https://api.telegram.org/bot7737977625:AAGqggWlEPqnkIOp52gzkNYTPeeBElMfPhg/setWebhook" -d "url=https://scientistically-precongenial-hermila.ngrok-free.dev/webhook"

